"""S4-T03: Generate real silence around hero speech.

Named tests required by the program:
  test_padding_contains_no_detected_speech
  test_adjacent_phrase_not_present
  test_slice_sample_count_exact
  test_slice_hash_deterministic
  test_master_change_invalidates_slice
"""
import subprocess
import sys
import json
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

import production_db as _db
import production_repo as _repo
from slice_continuous_lipsync import slice_hero_units
from timeline_utils import MASTER_SAMPLE_RATE, ms_to_samples, samples_to_ms


@pytest.fixture
def fresh_db(tmp_path, monkeypatch):
    db_file = str(tmp_path / "slice_test.db")
    monkeypatch.setenv("PRODUCTION_DB_PATH", db_file)
    _db._db_path_override = db_file
    _db.migrate(db_file)
    prod = _db.ensure_production("slice_test", seed="s", video_type="short", db_path=db_file)
    yield prod, db_file, tmp_path
    _db._db_path_override = None


def _make_master_wav(path: Path, duration_sec: float = 10.0):
    """Create a master WAV with a tone (simulating narration).
    Speech is represented by the tone; silence regions have no signal."""
    subprocess.run([
        "ffmpeg", "-y", "-f", "lavfi",
        "-i", f"sine=frequency=440:duration={duration_sec}",
        "-c:a", "pcm_s16le", "-ar", str(MASTER_SAMPLE_RATE), "-ac", "1",
        str(path),
    ], capture_output=True, check=True)


def _make_master_with_silence(path: Path, speech_start_sec: float, speech_end_sec: float, total_sec: float = 10.0):
    """Create a master WAV with silence before and after a speech segment.
    The speech segment is a 440Hz tone; the rest is silence."""
    # Generate silence for the full duration, then overlay tone in the speech region
    subprocess.run([
        "ffmpeg", "-y", "-f", "lavfi",
        "-i", f"anullsrc=channel_layout=mono:sample_rate={MASTER_SAMPLE_RATE}:duration={total_sec}",
        "-f", "lavfi", "-i", f"sine=frequency=440:duration={speech_end_sec - speech_start_sec}",
        "-filter_complex",
        f"[1:a]adelay={int(speech_start_sec*1000)}|{int(speech_start_sec*1000)}[delayed];"
        f"[0:a][delayed]amix=inputs=2:duration=first[a]",
        "-map", "[a]", "-c:a", "pcm_s16le", "-ar", str(MASTER_SAMPLE_RATE), "-ac", "1",
        str(path),
    ], capture_output=True, check=True)


def _measure_rms_energy(path: Path, start_sec: float, duration_sec: float) -> float:
    """Measure RMS energy of a segment of an audio file (dB)."""
    r = subprocess.run([
        "ffmpeg", "-y", "-ss", str(start_sec), "-t", str(duration_sec),
        "-i", str(path),
        "-af", "volumedetect",
        "-f", "null", "-",
    ], capture_output=True, text=True)
    for line in r.stderr.splitlines():
        if "mean_volume" in line:
            # line format: "mean_volume: -XX.XX dB"
            parts = line.split(":")
            if len(parts) >= 2:
                val = parts[1].strip().replace("dB", "").strip()
                return float(val)
    return -999.0


def test_padding_contains_no_detected_speech(fresh_db):
    """The silence padding regions of a hero slice contain no detectable speech
    energy — they are true digital silence generated by anullsrc."""
    prod, db_path, tmp_path = fresh_db
    master_wav = tmp_path / "master.wav"
    _make_master_with_silence(master_wav, speech_start_sec=2.0, speech_end_sec=5.0, total_sec=10.0)

    art = _repo.register_artifact(prod["id"], master_wav, "master_audio", db_path=db_path)

    # Speech is samples 96000..240000 (2s..5s at 48kHz)
    # Slice with 0.5s leading + 0.5s trailing silence
    lead_samples = ms_to_samples(500)
    trail_samples = ms_to_samples(500)
    speech_bounds = [{
        "render_unit_id": "ru_test",
        "speech_start_sample": 96000,
        "speech_end_sample": 240000,
        "leading_silence_samples": lead_samples,
        "trailing_silence_samples": trail_samples,
    }]

    output_dir = tmp_path / "slices"
    results = slice_hero_units(prod["id"], art["id"], output_dir, speech_bounds, db_path=db_path)
    assert len(results) == 1

    slice_path = Path(results[0]["slice_path"])
    assert slice_path.exists()

    # Measure energy in the leading silence region (first 0.4s)
    lead_energy = _measure_rms_energy(slice_path, 0.0, 0.4)
    # Digital silence should be very quiet (< -60 dB)
    assert lead_energy < -60.0, f"leading silence has energy {lead_energy}dB — speech leaked into padding"

    # Measure energy in the trailing silence region (last 0.4s)
    # Total slice duration ≈ 0.5 + 3.0 + 0.5 = 4.0s; trailing silence starts ~3.6s
    trail_energy = _measure_rms_energy(slice_path, 3.6, 0.4)
    assert trail_energy < -60.0, f"trailing silence has energy {trail_energy}dB — speech leaked into padding"


def test_adjacent_phrase_not_present(fresh_db):
    """The hero slice does NOT contain audio from adjacent master speech regions.

    We create a master with speech at 1-2s AND 3-4s (adjacent phrases).
    The slice extracts only 3-4s; the 1-2s phrase must NOT appear in the slice.
    """
    prod, db_path, tmp_path = fresh_db
    master_wav = tmp_path / "master_adjacent.wav"

    # Create master with two distinct tones: 1000Hz at 1-2s, 440Hz at 3-4s
    subprocess.run([
        "ffmpeg", "-y", "-f", "lavfi",
        "-i", f"anullsrc=channel_layout=mono:sample_rate={MASTER_SAMPLE_RATE}:duration=6.0",
        "-f", "lavfi", "-i", "sine=frequency=1000:duration=1.0",
        "-f", "lavfi", "-i", "sine=frequency=440:duration=1.0",
        "-filter_complex",
        "[1:a]adelay=1000|1000[t1];[2:a]adelay=3000|3000[t2];"
        "[0:a][t1][t2]amix=inputs=3:duration=first[a]",
        "-map", "[a]", "-c:a", "pcm_s16le", "-ar", str(MASTER_SAMPLE_RATE), "-ac", "1",
        str(master_wav),
    ], capture_output=True, check=True)

    art = _repo.register_artifact(prod["id"], master_wav, "master_audio", db_path=db_path)

    # Slice the 440Hz region (3-4s = samples 144000..192000) with 0.5s padding
    speech_bounds = [{
        "render_unit_id": "ru_adjacent",
        "speech_start_sample": 144000,
        "speech_end_sample": 192000,
        "leading_silence_samples": ms_to_samples(500),
        "trailing_silence_samples": ms_to_samples(500),
    }]

    output_dir = tmp_path / "slices_adj"
    results = slice_hero_units(prod["id"], art["id"], output_dir, speech_bounds, db_path=db_path)
    slice_path = Path(results[0]["slice_path"])

    # The 1000Hz tone (adjacent phrase at 1-2s) must NOT appear in the slice.
    # Verify by checking that the slice's speech region is ~440Hz, not 1000Hz.
    # We check the first 0.5s (should be silence) has no 1000Hz content.
    lead_energy = _measure_rms_energy(slice_path, 0.0, 0.4)
    assert lead_energy < -60.0, "adjacent phrase leaked into leading silence"


def test_slice_sample_count_exact(fresh_db):
    """The slice sample count matches speech + leading + trailing silence (or
    is padded to LIPSYNC_MIN if the total is shorter)."""
    prod, db_path, tmp_path = fresh_db
    master_wav = tmp_path / "master_exact.wav"
    _make_master_wav(master_wav, 10.0)
    art = _repo.register_artifact(prod["id"], master_wav, "master_audio", db_path=db_path)

    lead = ms_to_samples(500)
    trail = ms_to_samples(500)
    speech_start = 48000   # 1s
    speech_end = 240000    # 5s (4s of speech → total 5s, exceeds LIPSYNC_MIN=4s)
    expected_total = lead + (speech_end - speech_start) + trail

    speech_bounds = [{
        "render_unit_id": "ru_exact",
        "speech_start_sample": speech_start,
        "speech_end_sample": speech_end,
        "leading_silence_samples": lead,
        "trailing_silence_samples": trail,
    }]

    output_dir = tmp_path / "slices_exact"
    results = slice_hero_units(prod["id"], art["id"], output_dir, speech_bounds, db_path=db_path)
    slice_path = Path(results[0]["slice_path"])

    probe = _repo.probe_media(slice_path)
    actual_samples = int(probe.duration_ms * MASTER_SAMPLE_RATE / 1000)

    # No LIPSYNC_MIN padding needed (5s > 4s min)
    assert abs(actual_samples - expected_total) <= 48, (
        f"slice samples {actual_samples} != expected ~{expected_total} "
        f"(lead={lead} + speech={speech_end-speech_start} + trail={trail})")


def test_slice_hash_deterministic(fresh_db):
    """Slicing the same master with the same bounds produces the same SHA-256."""
    prod, db_path, tmp_path = fresh_db
    master_wav = tmp_path / "master_det.wav"
    _make_master_wav(master_wav, 10.0)
    art = _repo.register_artifact(prod["id"], master_wav, "master_audio", db_path=db_path)

    bounds = [{
        "render_unit_id": "ru_det",
        "speech_start_sample": 48000,
        "speech_end_sample": 144000,
        "leading_silence_samples": ms_to_samples(500),
        "trailing_silence_samples": ms_to_samples(500),
    }]

    out1 = tmp_path / "slices_det1"
    r1 = slice_hero_units(prod["id"], art["id"], out1, bounds, db_path=db_path)

    out2 = tmp_path / "slices_det2"
    r2 = slice_hero_units(prod["id"], art["id"], out2, bounds, db_path=db_path)

    assert r1[0]["sha256"] == r2[0]["sha256"], "same master + same bounds must produce same SHA"


def test_master_change_invalidates_slice(fresh_db):
    """A different master produces a different slice SHA (provenance-linked)."""
    prod, db_path, tmp_path = fresh_db

    # Master 1: 440Hz
    master1 = tmp_path / "master1.wav"
    _make_master_wav(master1, 10.0)
    art1 = _repo.register_artifact(prod["id"], master1, "master_audio", db_path=db_path)

    # Master 2: 880Hz (different content)
    master2 = tmp_path / "master2.wav"
    subprocess.run([
        "ffmpeg", "-y", "-f", "lavfi",
        "-i", "sine=frequency=880:duration=10.0",
        "-c:a", "pcm_s16le", "-ar", str(MASTER_SAMPLE_RATE), "-ac", "1",
        str(master2),
    ], capture_output=True, check=True)
    art2 = _repo.register_artifact(prod["id"], master2, "master_audio", db_path=db_path)

    bounds = [{
        "render_unit_id": "ru_inv",
        "speech_start_sample": 48000,
        "speech_end_sample": 144000,
        "leading_silence_samples": ms_to_samples(500),
        "trailing_silence_samples": ms_to_samples(500),
    }]

    r1 = slice_hero_units(prod["id"], art1["id"], tmp_path / "s1", bounds, db_path=db_path)
    r2 = slice_hero_units(prod["id"], art2["id"], tmp_path / "s2", bounds, db_path=db_path)

    assert r1[0]["sha256"] != r2[0]["sha256"], "different master must produce different slice SHA"

    # Provenance: each slice artifact references its own master via metadata
    conn = _db.connect(db_path)
    meta1 = json.loads(conn.execute(
        "SELECT metadata_json FROM artifacts WHERE id=?", (r1[0]["artifact_id"],)
    ).fetchone()["metadata_json"])
    meta2 = json.loads(conn.execute(
        "SELECT metadata_json FROM artifacts WHERE id=?", (r2[0]["artifact_id"],)
    ).fetchone()["metadata_json"])
    conn.close()
    assert meta1["master_sha256"] != meta2["master_sha256"], "each slice must reference its own master SHA"
    assert meta1["master_artifact_id"] == art1["id"]
    assert meta2["master_artifact_id"] == art2["id"]
