#!/usr/bin/env python3
"""narrative_speed.py — measure spoken-narrative pacing of video/audio clips.

Why this exists
---------------
At scale we generate many talking-head clips (one narrator voice: James
Harrington). For a multi-clip piece to feel coherent, every segment must
share the SAME perceived speaking pace. "Pace" is words-per-second (WPS)
measured over *active speech* (excluding leading/trailing silence and the
pauses between phrases).

This tool measures, per clip:
  - total duration
  - speech span (first sound -> last sound)
  - active speech seconds (sum of non-silent regions)
  - leading / trailing silence (the dead air that makes cuts feel slow)
  - longest internal pause
  - WPS over active speech   (requires --words: the clip's word count)
  - SPS over active speech   (syllable estimate; works without a transcript)

It can also RECOMMEND a per-clip playback-speed multiplier to align every
clip to a chosen reference clip's pace, so segments match by construction.

Word counts: at scale the script is generated by the pipeline, so the word
count of every clip is known for free — pass it with --words. For legacy
clips with no script, omit --words and use the syllable proxy (SPS), or
transcribe separately.

Usage
-----
  # single clip, with known word count
  python3 tools/narrative_speed.py measure clip.mp4 --words 22

  # compare several clips and get speeds to align them to clip #2 (index 1)
  python3 tools/narrative_speed.py align \
      a.mp4:22 b.mp4:31 c.mp4:18 --reference 1

  # reference may also be a target WPS instead of a clip index
  python3 tools/narrative_speed.py align a.mp4:22 b.mp4:31 --target-wps 2.6

Notes
-----
- Silence threshold default -45 dB catches quiet beds; tune with --noise.
- "active speech" uses silencedetect to subtract pauses, so a clip with long
  gaps is not mistaken for fast speech.
- WPS scales linearly with playback speed, so to hit a target WPS for a clip:
        new_speed = current_speed * (target_wps / measured_wps)
  Here measured_wps is at source speed (current_speed = 1.0).
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass, asdict
from pathlib import Path

DEFAULT_NOISE_DB = -45.0   # below this = silence (catches quiet music beds)
DEFAULT_MIN_SIL = 0.18     # min silence duration to count as a pause (s)


def _run(cmd: list[str]) -> str:
    r = subprocess.run(cmd, capture_output=True, text=True)
    # ffmpeg writes silencedetect to stderr; return combined
    return (r.stdout or "") + (r.stderr or "")


def probe_duration(path: Path) -> float:
    out = _run([
        "ffprobe", "-v", "error", "-show_entries", "format=duration",
        "-of", "default=noprint_wrappers=1:nokey=1", str(path),
    ])
    try:
        return float(out.strip().splitlines()[0])
    except (ValueError, IndexError):
        raise FileNotFoundError(f"could not probe duration (missing or unreadable): {path}")


def silence_intervals(path: Path, noise_db: float, min_sil: float) -> list[tuple[float, float]]:
    """Return list of (start, end) silent intervals."""
    out = _run([
        "ffmpeg", "-hide_banner", "-i", str(path),
        "-af", f"silencedetect=noise={noise_db}dB:d={min_sil}",
        "-f", "null", "/dev/null",
    ])
    starts = [float(m) for m in re.findall(r"silence_start: ([0-9.]+)", out)]
    ends = [float(m) for m in re.findall(r"silence_end: ([0-9.]+)", out)]
    intervals = []
    for i, s in enumerate(starts):
        e = ends[i] if i < len(ends) else None
        intervals.append((s, e))
    return intervals


def estimate_syllables(word_count: int) -> float:
    """Rough syllable estimate when only a word count is known (~1.4/word for EN)."""
    return word_count * 1.4


@dataclass
class ClipPace:
    path: str
    duration: float
    speech_start: float
    speech_end: float
    speech_span: float          # speech_end - speech_start
    active_speech: float        # span minus internal pauses
    leading_silence: float
    trailing_silence: float
    longest_pause: float
    words: int | None
    wps: float | None           # words / active_speech
    wps_span: float | None      # words / speech_span (incl. pauses)


def measure(path: Path, words: int | None,
            noise_db: float = DEFAULT_NOISE_DB,
            min_sil: float = DEFAULT_MIN_SIL) -> ClipPace:
    dur = probe_duration(path)
    sils = silence_intervals(path, noise_db, min_sil)

    # leading silence: a silence interval starting at ~0
    leading = 0.0
    trailing = 0.0
    internal_pause_total = 0.0
    longest_pause = 0.0

    speech_start = 0.0
    speech_end = dur

    for (s, e) in sils:
        e_eff = e if e is not None else dur
        is_leading = s <= 0.05
        is_trailing = (e is None) or (abs(e_eff - dur) <= 0.05)
        length = e_eff - s
        if is_leading:
            leading = max(leading, e_eff)
            speech_start = max(speech_start, e_eff)
        elif is_trailing:
            trailing = max(trailing, dur - s)
            speech_end = min(speech_end, s)
        else:
            internal_pause_total += length
            longest_pause = max(longest_pause, length)

    speech_span = max(speech_end - speech_start, 0.0)
    active_speech = max(speech_span - internal_pause_total, 0.01)

    wps = (words / active_speech) if words else None
    wps_span = (words / speech_span) if (words and speech_span > 0) else None

    return ClipPace(
        path=str(path),
        duration=round(dur, 3),
        speech_start=round(speech_start, 3),
        speech_end=round(speech_end, 3),
        speech_span=round(speech_span, 3),
        active_speech=round(active_speech, 3),
        leading_silence=round(leading, 3),
        trailing_silence=round(trailing, 3),
        longest_pause=round(longest_pause, 3),
        words=words,
        wps=round(wps, 3) if wps else None,
        wps_span=round(wps_span, 3) if wps_span else None,
    )


def _fmt(p: ClipPace) -> str:
    name = Path(p.path).name
    lines = [
        f"{name}",
        f"  duration         {p.duration:6.2f}s",
        f"  speech span      {p.speech_span:6.2f}s  ({p.speech_start:.2f} -> {p.speech_end:.2f})",
        f"  active speech    {p.active_speech:6.2f}s",
        f"  leading silence  {p.leading_silence:6.2f}s",
        f"  trailing silence {p.trailing_silence:6.2f}s  <- dead air before next cut",
        f"  longest pause    {p.longest_pause:6.2f}s",
    ]
    if p.wps is not None:
        lines.append(f"  WPS (active)     {p.wps:6.2f}  words/s")
        lines.append(f"  WPS (incl pause) {p.wps_span:6.2f}  words/s")
    else:
        lines.append("  WPS              n/a  (pass words for this clip)")
    return "\n".join(lines)


def cmd_measure(args):
    p = measure(Path(args.clip), args.words, args.noise, args.min_sil)
    if args.json:
        print(json.dumps(asdict(p), indent=2))
    else:
        print(_fmt(p))


def _parse_clip_arg(token: str) -> tuple[Path, int | None]:
    """'path.mp4:22' -> (Path, 22); 'path.mp4' -> (Path, None)."""
    if ":" in token and not token[1:3] == ":\\":
        path, _, w = token.rpartition(":")
        if w.isdigit():
            return Path(path), int(w)
    return Path(token), None


def cmd_align(args):
    parsed = [_parse_clip_arg(t) for t in args.clips]
    paces = [measure(p, w, args.noise, args.min_sil) for (p, w) in parsed]

    print("=== measured pace ===")
    for p in paces:
        print(_fmt(p))
        print()

    # determine target WPS
    if args.target_wps is not None:
        target = args.target_wps
        ref_label = f"target {target:.2f} wps"
    else:
        idx = args.reference
        if idx < 0 or idx >= len(paces):
            sys.exit(f"--reference {idx} out of range (0..{len(paces)-1})")
        if paces[idx].wps is None:
            sys.exit("reference clip has no word count; provide :words or use --target-wps")
        target = paces[idx].wps
        ref_label = f"{Path(paces[idx].path).name} ({target:.2f} wps)"

    print(f"=== recommended per-clip speed to match {ref_label} ===")
    print("(speed>1 = faster; apply as setpts/atempo in the editor)")
    for p in paces:
        if p.wps is None:
            print(f"  {Path(p.path).name:24s}  speed n/a (need word count)")
            continue
        speed = target / p.wps
        tag = "  <- reference" if abs(speed - 1.0) < 1e-3 else ""
        print(f"  {Path(p.path).name:24s}  x{speed:5.3f}{tag}")


def main(argv=None):
    ap = argparse.ArgumentParser(description="Measure narrative pacing (WPS) of clips.")
    sub = ap.add_subparsers(dest="cmd", required=True)

    m = sub.add_parser("measure", help="measure one clip")
    m.add_argument("clip")
    m.add_argument("--words", type=int, default=None)
    m.add_argument("--noise", type=float, default=DEFAULT_NOISE_DB)
    m.add_argument("--min-sil", type=float, default=DEFAULT_MIN_SIL)
    m.add_argument("--json", action="store_true")
    m.set_defaults(func=cmd_measure)

    a = sub.add_parser("align", help="compare clips + recommend speeds to match a reference")
    a.add_argument("clips", nargs="+", help="path[:words] tokens")
    a.add_argument("--reference", type=int, default=0, help="index of reference clip (default 0)")
    a.add_argument("--target-wps", type=float, default=None, help="target WPS instead of a reference clip")
    a.add_argument("--noise", type=float, default=DEFAULT_NOISE_DB)
    a.add_argument("--min-sil", type=float, default=DEFAULT_MIN_SIL)
    a.set_defaults(func=cmd_align)

    args = ap.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
